### NumPy
**Followed** : "NumPy tutorial: Beginner to Advanced" from Kaggle ([Link](https://www.kaggle.com/code/iamramzanai/numpy-tutorial-beginner-to-advanced#1.-Introduction))

In [2]:
import numpy as np

### 1. Array Creation

In [11]:
import array
arr = array.array('i',[1,2,3,4,5])
print(arr)
for i in range(0,3):
    print(arr[i], end=" ")

array('i', [1, 2, 3, 4, 5])
1 2 3 

**1.1 Arange method** : Syntax: np.arange(start, step, stop, dtype)

In [24]:
a = np.arange(10).reshape(5,2)
print(a, "\n")

b = np.arange(25, 225, 25).reshape(2,4)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

[[ 25  50  75 100]
 [125 150 175 200]]


**1.2 Zero method** : Syntax: np.zeros(number-of-zeros, dtype)

In [36]:
c = np.zeros(4, int).reshape(2,2)
print(c, "\n")

d = np.zeros(7, float).reshape(7,1)
print(d)

[[0 0]
 [0 0]] 

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


**1.3 All-one arrays** : np.ones(number-of-ones-in-array, dtype)
<br>
                     np.ones_like(array, dtype)

In [48]:
e = np.ones(9, int).reshape(3,3)
print(e, "\n")

print(arr)
f = np.ones_like(arr, int)#creates an array of given shape and type and a given array with only ones
print(f)

[[1 1 1]
 [1 1 1]
 [1 1 1]] 

array('i', [1, 2, 3, 4, 5])
[1 1 1 1 1]


**1.4 Linspace method** : np.linspace(start, stop, number-of-digits-in-array, dtype, restep=T/F)

In [63]:
g = np.linspace(100, 200, 10, retstep=False, dtype=int)
print(g, "\n")

h = np.linspace(10,20,10, dtype=int).reshape(5,2)
print(h)

[100 111 122 133 144 155 166 177 188 200] 

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 20]]


**1.5 Identity matrix** 

In [74]:
i = np.eye(3, dtype=int)
print(i, "\n")

j = np.eye(9, dtype=complex)
print(j)

[[1 0 0]
 [0 1 0]
 [0 0 1]] 

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j]]


**1.6 Empty & full array** 

In [78]:
k = np.empty((5,1), dtype=int)
print(k, "\n")

l = np.full([4,4], 10, dtype=int)
print(l)

[[4611686018427387904]
 [4612248968380809216]
 [4612811918334230528]
 [4613374868287651840]
 [4613937818241073152]] 

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


### 2. Array Manipulation

**2.1 Copy and view array**

In [90]:
x = np.array([10,20,30,40])
print(x)

v = x.view()
x[1]=90
print(v)
print(x)

#both their memory locations i.e. IDs are the same
print(id(x), id(v))

[10 20 30 40]
[10 90 30 40]
[10 90 30 40]
2089166570480 2089166571824


In [95]:
y = np.array(x)
print(y)

c=y.copy()
print(c)

c[1]=20
print(y)#doesnt change when copy is changed
print(c)

print(id(y), id(c))#different memory locations

[10 90 30 40]
[10 90 30 40]
[10 90 30 40]
[10 20 30 40]
2089166574512 2089166576336


**2.2 Appending values at the end**

In [9]:
a = np.array([[1,2,3],[4,5,6]]).reshape(2,3)
print(a)

append_col = np.arange(7,13).reshape(2,3)
print(append_col, "\n")

a_col = np.append(a, append_col, axis=0)
print(a_col, "\n")

append_row = np.arange(7,10).reshape(3,1)
print(append_row)

a_row = np.append(a, append_row)
print(a_row)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[7]
 [8]
 [9]]
[1 2 3 4 5 6 7 8 9]


**2.3 Concat index vice**

In [19]:
a = np.array([3,4,5])
b = np.array([9,10,39])
c = np.hstack((a,b))
print(c)

d = np.dstack((a,b))
print(d)

[ 3  4  5  9 10 39]
[[[ 3  9]
  [ 4 10]
  [ 5 39]]]


**2.4 Split arrays**

In [23]:
print(np.split(c,3))

[array([3, 4]), array([5, 9]), array([10, 39])]


**2.5 Compare arrays**

In [ ]:
d = d.reshape(1,6)
e = c == d
print(e)

[[ 3  9  4 10  5 39]]
[ 3  4  5  9 10 39]
[[ True False False False False  True]]


**2.6 Union of 1D arrays**

In [31]:
print(c,d)
e = np.union1d(c,d)
print(e)

[ 3  4  5  9 10 39] [[ 3  9  4 10  5 39]]
[ 3  4  5  9 10 39]


**2.7 Trimming zeroes**

In [33]:
array = np.array([2,3,4,5,0,0,0,0])
f = np.trim_zeros(array)
print(f)

[2 3 4 5]


### 3. Matrix functions in NumPy

In [38]:
x = np.array([[1, 2], [4, 5]]) 
y = np.array([[7, 8], [9, 10]]) 
# +,-,* and / can be done

z = np.dot(x,y)
print(z)

z = np.sqrt(x)
print(z)

z = np.sum(y,axis=0)
print(z)

z = x.T
print(z)

[[25 28]
 [73 82]]
[[1.         1.41421356]
 [2.         2.23606798]]
[16 18]
[[1 4]
 [2 5]]
